menu:
  Home: /
  Archives: /archives

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter: mikedeboer
github: mikedeboer

fancybox: true
google_analytics:
rss: /atom.xml
